### ISSUE TITLE
Slugify Urls

### ISSUE THREAD

**Issue by remiliacorp** [remiliacorp/exocore#1]
URLs should be slugified (spaces turned to hyphen). Not sure why I'm unable to get this working, its a standard jekyll config setting, should be:
`permalink: /:categories/:slugify/`

Default config.yaml is set to `permalink: pretty` which should unpack to `/:categories/:year/:month/:day/:title/`, even though the actual permalink format looks like `permalink: /:categories/:title` which makes me suspect config.yaml is being overridden somewhere.

**Comment by hot-domme** [comment]
FIXED:
Looks like the each collection needs its own permalink defined, and the global setting only extends to pages(?) — this was working before, not sure why it broke.

I've left all collection permalinks as: `permalink: /:collection/:slug`, so they look like `/articles/exocore-installation-instructions`.

However, they can be changed individually in _config.
