### ISSUE TITLE
Hexcode titles for Obsidian wiki notes

### ISSUE THREAD

**Issue by remiliacorp** [remiliacorp/exocore#14]
Obsidian currently not working for generating wiki titles as hex codes; this should be possible with its Templater plugin though

**Comment by hot-domme** [comment]
FIXED — A small javascript function [here](https://github.com/remiliacorp/exocore/blob/master/assets/templater-scripts/randomhex.js) generates a random hex, and this is applied as both the filename and a first-level header in the body of the document.

With VSCode we were using a standard hexcode tag in their template plugin, but this is much better. We can make the hex any length we want by altering the JS, or come up with a specific format for the identifier. For now, I left it as a 16-bit hex code (6 digits/letters). There area ~17 million permutations, so we shouldn't have to worry about double-ups.

**Comment by hot-domme** [comment]
All notes now follow the correct templates of the folder you're in when they are created — for instance, if you have a wikinote open, cmd+N creates a new wikinote with the correct template, hexcode etc
