### ISSUE TITLE
Anchor tags shouldn’t show up on the profile side bar for Articles, Journals etc

### ISSUE THREAD

**Issue by remiliacorp** [remiliacorp/exocore#15]
Self-explanatory

**Comment by hot-domme** [comment]
Fixed — it was a problem with anchor-js [here](https://github.com/remiliacorp/exocore/blob/master/exocore/_layouts/default.html#:~:text=%3Cscript%3Eanchors.add(%27.post%2Dcontent%20*%27)%3B%3C/script%3E)
