### ISSUE TITLE
Summaries include wikilinks markdown syntax

### ISSUE THREAD

**Issue by remiliacorp** [remiliacorp/exocore#17]
They don't render correctly in the summary index cards, e.g. showing `[[Link]]` instead of converting it into an actual link

eg 
![Screen Shot 2022-09-28 at 3 03 02 PM](https://user-images.githubusercontent.com/80489490/192877960-eb5aeb32-2e66-43f7-b52e-67c2c0bd51aa.png)

**Comment by hot-domme** [comment]
fixed
