### ISSUE TITLE
Should replace the emoji return symbol with unicode: ↲

### ISSUE THREAD

**Issue by remiliacorp** [remiliacorp/exocore#22]
The emoji return is too out of place:
![Screen Shot 2022-09-28 at 3 03 14 PM](https://user-images.githubusercontent.com/80489490/192877814-94a26714-8239-4208-b721-564e311e48ca.png)

This version wont render as an emoji on browsers: ↲

**Comment by hot-domme** [comment]
FIXED

I've changed the footnote return glyph to  `↲` and added the option to change it to anything in _config [here](https://github.com/remiliacorp/exocore/blob/master/_config.yml#L51)
