### ISSUE TITLE
Draft status

### ISSUE THREAD

**Issue by remiliacorp** [remiliacorp/exocore#23]
Frontmatter for published: draft; if "draft" its published but visually indicated its a work in progress

**Comment by hot-domme** [comment]
FIXED

I've made [this scrapbook](https://exocore.netlify.app/scrapbook/predictive%20processing%20and%20the%20free%20energy%20principle/) a draft for demonstration.

Front matter options are:

```
Published: true
Published: false
Published: draft
```

NOTE: when accessing the above three acceptable values with liquid templating, true/false are interpreted as booleans, while 'draft' is interpreted as a string, so the 'draft' value needs quotations (but ONLY in the templates, in the front matter they work just fine written as above, so this is irrelevant to average users.)

In liquid it's:
```
{% if page.published == true %}
{% if page.published == false %}
```
or
```
{% if page.published == "draft" %}
```
