### ISSUE TITLE
Link to top of page at bottom of each page

### ISSUE THREAD

**Issue by remiliacorp** [remiliacorp/exocore#7]
There should be a little text to click to go back to top at the bottom of each post and page, like this `↑ Return ↑` on edith reisen

![Screen Shot 2022-09-28 at 2 54 04 PM](https://user-images.githubusercontent.com/80489490/192876195-6a7d6048-9557-4dd2-93e1-1138374fecda.png)

**Comment by hot-domme** [comment]
added
